"""Storage backends for the bitemporal datom log.

The :class:`Store` Protocol is the seam between the pure-data ``DB`` /
``DBView`` layer and whatever backend happens to be under the hood —
in-memory for tests, SQLite for zero-ops single-operator deploys, Postgres
for production.

Per agent1-fact-spec §4 the production layout uses 5 primary indexes
(EAVT/AEVT/AVET/VAET, plus VT-E for bitemporal ranges) and a log-ordered
index for ``since(t)`` replication. Those indexes are created by the SQL
migration in ``migrations/0001_datom_log.sql``; this module just loads that
file into any DB-API-2 connection.

Concurrency contract (ARIS Round 3 P-concurrency)
-------------------------------------------------
**GIL doesn't protect you — assume you're in a multi-worker deployment.**
The old ``next_tx()`` + ``append()`` pair is a TOCTOU race: two writers
can both read ``MAX(tx)=N`` before either commits and then both insert
with ``tx=N+1``. The GIL happens to serialise pure-Python paths under
light load, but any SQLite I/O releases it — and a multi-process
(gunicorn, uvicorn workers) deployment has no GIL at all between writers.

The authoritative atomic primitive is :meth:`Store.allocate_and_append`,
which allocates the next tx id AND appends all provided datoms in a
single critical section. On SQLite that section is a ``BEGIN IMMEDIATE``
transaction — the writer lock is grabbed before the ``MAX(tx)`` read so
the read and the insert are serialised against any other writer. On
InMemoryStore the section is held under a ``threading.Lock``. On Postgres
the same pattern maps onto a ``SELECT ... FOR UPDATE`` or a ``SERIAL`` /
``GENERATED BY DEFAULT AS IDENTITY`` column (Phase 2).

:meth:`Store.next_tx` remains on the Protocol for read-only inspection
(tests, admin probes) and is implemented as a thin wrapper that does NOT
allocate — it returns the id that the *next* ``allocate_and_append`` call
would assign. Callers that need a tx id MUST use ``allocate_and_append``
to get it atomically with the write; treating ``next_tx`` as an allocator
will race.
"""

from __future__ import annotations

import sqlite3
import threading
from contextlib import contextmanager, nullcontext
from datetime import datetime
from pathlib import Path
from typing import Any, ContextManager, Iterable, Iterator, Protocol, runtime_checkable

from persistence.fact.datom import Datom
from persistence.store._codec import (
    TX_PLACEHOLDER as _CODEC_TX_PLACEHOLDER,
    TextDatomCodec,
    with_tx as _shared_with_tx,
)

_MIGRATION_DIR = Path(__file__).with_suffix("").parent / "migrations"

# Module-level codec instance — shared by SQLiteStore (encode +
# decode) and re-exported as the SQLite/text wire shape. PG2 (Phase 1
# stream #165) consolidates the previously module-local ``_encode`` /
# ``_decode`` helpers into ``persistence.store._codec.TextDatomCodec``;
# the names below are kept as thin module-level shims so existing
# call-sites and any external imports of ``persistence.fact.store._encode``
# / ``_decode`` / ``_with_tx`` continue to resolve.
_codec = TextDatomCodec()


def load_migrations() -> list[tuple[str, str]]:
    """Return ``[(name, sql), ...]`` for every SQL file in ``migrations/``."""
    return sorted(
        (p.name, p.read_text(encoding="utf-8"))
        for p in _MIGRATION_DIR.glob("*.sql")
    )


@runtime_checkable
class Store(Protocol):
    """Minimum contract every backend must satisfy.

    Backends are intentionally dumb. All bitemporal logic (auto-retraction,
    as-of, branch) lives in :class:`~persistence.fact.db.DB` over an iterable
    of datoms; the store's only job is durable append + ordered retrieval.

    PG3 extension (ADR-15 W2)
    -------------------------

    The Protocol gains TWO additive methods in v0.8 — :meth:`_txn` (store-
    level transaction context-manager) and :meth:`transact_serializable`
    (atomic primitive for cross-process correctness). Both have default
    implementations on InMemoryStore + SQLiteStore that preserve their
    existing semantics: ``_txn()`` defaults to a ``nullcontext()`` (no
    real transaction — the existing per-method critical sections under
    ``_lock`` already provide single-process atomicity); ``transact_serializable``
    defaults to a wrapper around :meth:`allocate_and_append` (or, when
    ``tx_time`` is provided, a manual append at the requested tx_time).
    PostgresStore overrides both with the SERIALIZABLE-transaction +
    ``tx_allocator``-row-lock + ``audit_chain_lock``-row-lock shape.

    Adapters bound to the original 6 methods (``append`` /
    ``allocate_and_append`` / ``all_datoms`` / ``since`` / ``mark_invalidated``
    / ``next_tx``) continue to work unchanged. New code that wants the
    multi-process atomicity guarantee opts into ``transact_serializable``.
    """

    def append(self, datoms: Iterable[Datom]) -> None:
        """Append datoms to the log. Must preserve insertion order.

        Low-level: does NOT allocate a tx id. Callers must already know
        the ids they want on each datom. Prefer
        :meth:`allocate_and_append` for transactional writes.
        """
        ...

    def allocate_and_append(
        self, datoms: Iterable[Datom]
    ) -> list[Datom]:
        """Atomically allocate a monotonic tx id and append datoms.

        Assigns every datom in the iterable the SAME freshly-allocated
        tx id (the log-transaction semantics match agent1-fact-spec §2).
        Returns the list of datoms with ``tx`` set. An empty iterable is
        a no-op and burns no tx id.

        Concurrency guarantee: the allocation and the write live in a
        single critical section — ``BEGIN IMMEDIATE`` on SQLite,
        ``threading.Lock`` on InMemoryStore — so two concurrent callers
        cannot both be assigned the same tx. See the module docstring
        for why the GIL is not enough.
        """
        ...

    def all_datoms(self) -> Iterator[Datom]:
        """Yield every datom in insertion order. This is the log."""
        ...

    def since(self, tx_time: datetime) -> Iterator[Datom]:
        """Yield datoms whose tx_time is strictly greater than ``tx_time``."""
        ...

    def mark_invalidated(self, tx: int, invalidated_by_tx: int) -> None:
        """Update every datom with ``tx`` == ``tx`` to set invalidated_by.

        Used by the transactor to stamp a superseded cardinality-one datom
        after the new assert lands. The original row's immutability is
        preserved at the level of ``e, a, v, tx_time, op`` — only the
        pointer changes.
        """
        ...

    def next_tx(self) -> int:
        """Return the id that the next ``allocate_and_append`` call would assign.

        **Read-only probe — does NOT reserve the id.** Two callers that use
        this as an allocator will race. Use :meth:`allocate_and_append` to
        atomically get an id.

        Tx allocation lives on the Store (not on a module-level counter)
        so two Stores backed by different files / databases do not collide,
        and a Store restored from an existing log resumes at ``max(tx)+1``
        instead of overwriting row 1 (ARIS R3 F10).
        """
        ...

    # ------- Additive Protocol methods (PG3 / ADR-15 W2) ------------------

    def _txn(self) -> ContextManager[Any]:
        """Open a store-level transaction; yield a backend-native handle.

        Per ADR-15 W2 this is the store-level transaction context-manager.
        On clean exit the transaction COMMITs; on exception ROLLBACK +
        re-raise. The yielded handle's exact type is backend-specific:

        - ``InMemoryStore`` — yields ``None`` (no real transaction; the
          existing per-method ``_lock`` critical sections give single-
          process atomicity).
        - ``SQLiteStore`` — yields ``None`` (the existing per-method
          ``BEGIN IMMEDIATE`` critical sections give single-process
          atomicity; ``_txn()`` is a no-op pass-through so the higher-
          level transact_serializable shape still works).
        - ``PostgresStore`` — yields the active :class:`psycopg.Cursor`
          on a SERIALIZABLE-mode connection.

        Default impl on InMemoryStore + SQLiteStore returns
        :func:`contextlib.nullcontext` so existing in-process callers
        see no behaviour change.
        """
        ...

    def transact_serializable(
        self,
        datoms: Iterable[Datom],
        *,
        tx_time: datetime | None = None,
    ) -> int:
        """Atomically allocate a tx-id and insert ``datoms`` under serialisable isolation.

        Per ADR-15 W2 + ADR-13 this is the atomic primitive for cross-
        process correctness. The contract:

        1. Open a store-level transaction (see :meth:`_txn`).
        2. Allocate a monotonic tx-id (under ``tx_allocator`` row lock on
           PostgresStore; under ``_lock`` mutex on InMemory / SQLite).
        3. If any datom in ``datoms`` is audit-shaped (``a`` starts with
           ``"audit/"``), additionally serialise on the audit-chain head
           (``audit_chain_lock`` row on PostgresStore; ``_lock`` mutex on
           InMemory / SQLite).
        4. Stamp every datom with the allocated tx-id; if ``tx_time`` is
           supplied, override each datom's ``tx_time`` with it (this is
           how ADR-13 preserves the audit handler's ``recorded_at``
           through the migration).
        5. INSERT the batch.
        6. COMMIT — releases the row locks.

        Args:
            datoms: iterable of :class:`Datom`. The ``tx`` field on each
                input datom is ignored; the allocator picks the real
                value. Empty iterable is a no-op and burns no tx-id.
            tx_time: when supplied, every datom is stamped with this
                ``tx_time`` (overrides the datom's own value). Used by
                :func:`persistence.repl._audit.persist_repl_audit` to
                preserve the audit handler's ``recorded_at`` instant per
                ADR-13. When ``None`` (default), each datom's existing
                ``tx_time`` is preserved unchanged.

        Returns:
            The freshly-allocated tx-id (int) shared by all inserted
            datoms. ``0`` if ``datoms`` is empty.
        """
        ...


# ---------------------------------------------------------------------------
# InMemoryStore — reference backend, fastest path for tests and the CLI demo.
# ---------------------------------------------------------------------------
class InMemoryStore:
    """Simple list-backed reference implementation. Thread-safe within a
    single process via :class:`threading.Lock`. Not shared across processes
    (no file-backing) — use SQLite/Postgres for multi-worker deploys.
    """

    def __init__(self) -> None:
        self._log: list[Datom] = []
        # RLock (reentrant): _run() holds it across conflict-check + db.transact();
        # allocate_and_append re-acquires on the same thread — safe with RLock.
        self._lock = threading.RLock()

    def append(self, datoms: Iterable[Datom]) -> None:
        with self._lock:
            self._log.extend(datoms)

    def allocate_and_append(self, datoms: Iterable[Datom]) -> list[Datom]:
        """Allocate next tx id and append, atomically under ``_lock``."""
        materialised = list(datoms)
        if not materialised:
            return []
        with self._lock:
            tx = (max((d.tx for d in self._log), default=0)) + 1
            out = [_with_tx(d, tx) for d in materialised]
            self._log.extend(out)
        return out

    def all_datoms(self) -> Iterator[Datom]:
        # Snapshot so the caller iterates a stable list even if append races.
        with self._lock:
            snapshot = list(self._log)
        return iter(snapshot)

    def since(self, tx_time: datetime) -> Iterator[Datom]:
        return (d for d in self.all_datoms() if d.tx_time > tx_time)

    def mark_invalidated(self, tx: int, invalidated_by_tx: int) -> None:
        with self._lock:
            for i, d in enumerate(self._log):
                if d.tx == tx and d.invalidated_by is None and d.op == "assert":
                    # dataclass is frozen → produce a new instance
                    self._log[i] = Datom(
                        e=d.e,
                        a=d.a,
                        v=d.v,
                        tx=d.tx,
                        tx_time=d.tx_time,
                        valid_from=d.valid_from,
                        valid_to=d.valid_to,
                        op=d.op,
                        provenance=d.provenance,
                        invalidated_by=invalidated_by_tx,
                    )

    def next_tx(self) -> int:
        """``max(tx across the log) + 1``; starts at 1 for an empty store.

        Read-only probe. To atomically allocate, use :meth:`allocate_and_append`.
        """
        with self._lock:
            if not self._log:
                return 1
            return max(d.tx for d in self._log) + 1

    # ------- Additive Protocol methods (PG3 / ADR-15 W2) ------------------

    @contextmanager
    def _txn(self):
        """Default transaction context — InMemoryStore has no ACID layer.

        Single-process atomicity is provided by the existing per-method
        ``_lock`` critical sections (``append`` / ``allocate_and_append``
        / ``mark_invalidated`` all hold the lock). ``_txn()`` is therefore
        a pass-through that yields ``None``; tests that bind to the
        Protocol method get a clean no-op shape.
        """
        with nullcontext():
            yield None

    def transact_serializable(
        self,
        datoms: Iterable[Datom],
        *,
        tx_time: datetime | None = None,
    ) -> int:
        """Default impl: route through :meth:`allocate_and_append` under ``_lock``.

        Per ADR-15 W2 the InMemoryStore default impl preserves existing
        single-process semantics — the in-process ``_lock`` mutex is the
        existing serialisation gate. When ``tx_time`` is provided, every
        datom's ``tx_time`` is overridden with it before insertion (this
        is how ADR-13 preserves the audit handler's ``recorded_at``).
        """
        materialised = list(datoms)
        if not materialised:
            return 0
        if tx_time is not None:
            materialised = [_replace_tx_time(d, tx_time) for d in materialised]
        out = self.allocate_and_append(materialised)
        return int(out[0].tx)


# ---------------------------------------------------------------------------
# SQLiteStore — persistent backend used by the test suite. The schema is the
# same one the Postgres migration produces, so switching backends is just a
# DSN change for any operator willing to run Postgres.
# ---------------------------------------------------------------------------
class SQLiteStore:
    """SQLite-backed datom log. Uses the shared migration SQL."""

    def __init__(self, path: str = ":memory:") -> None:
        self._path = path
        # check_same_thread=False is safe because we serialize via _lock;
        # SQLite itself handles concurrent readers fine.
        self._conn = sqlite3.connect(
            path, detect_types=sqlite3.PARSE_DECLTYPES, check_same_thread=False
        )
        self._conn.row_factory = sqlite3.Row
        # isolation_level=None → we manage transactions explicitly so
        # BEGIN IMMEDIATE actually starts a reserved-write transaction
        # (the default implicit mode would start a deferred one).
        self._conn.isolation_level = None
        # RLock matches InMemoryStore: _run() in persistence.txn holds this
        # across the conflict-check + db.transact() sequence; the inner
        # allocate_and_append re-acquires on the same thread.
        self._lock = threading.RLock()
        self._apply_migrations()

    def _apply_migrations(self) -> None:
        # executescript runs in its own auto-commit wrapper even with
        # isolation_level=None, so no explicit BEGIN needed here.
        for _name, sql in load_migrations():
            self._conn.executescript(sql)

    # ---- Protocol methods ------------------------------------------------
    def append(self, datoms: Iterable[Datom]) -> None:
        rows = [_encode(d) for d in datoms]
        if not rows:
            return
        with self._lock:
            try:
                self._conn.execute("BEGIN IMMEDIATE")
                self._conn.executemany(
                    """
                    INSERT INTO datom_log
                      (e, a, v, tx, tx_time, valid_from, valid_to, op,
                       provenance, invalidated_by)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    rows,
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    def allocate_and_append(self, datoms: Iterable[Datom]) -> list[Datom]:
        """Atomic allocate-and-append under ``BEGIN IMMEDIATE``.

        The SQLite writer lock is grabbed on ``BEGIN IMMEDIATE``, so the
        ``MAX(tx)`` read and the ``INSERT`` are serialised against any
        other concurrent writer even without the in-process
        :class:`threading.Lock` (which we keep anyway for tidy
        single-process behaviour).
        """
        materialised = list(datoms)
        if not materialised:
            return []
        with self._lock:
            try:
                self._conn.execute("BEGIN IMMEDIATE")
                cur = self._conn.execute(
                    "SELECT COALESCE(MAX(tx), 0) + 1 FROM datom_log"
                )
                row = cur.fetchone()
                tx = int(row[0] if row is not None else 1)
                out = [_with_tx(d, tx) for d in materialised]
                self._conn.executemany(
                    """
                    INSERT INTO datom_log
                      (e, a, v, tx, tx_time, valid_from, valid_to, op,
                       provenance, invalidated_by)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    [_encode(d) for d in out],
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise
        return out

    def all_datoms(self) -> Iterator[Datom]:
        with self._lock:
            cur = self._conn.execute(
                "SELECT * FROM datom_log ORDER BY seq ASC"
            )
            rows = cur.fetchall()
        return (_decode(r) for r in rows)

    def since(self, tx_time: datetime) -> Iterator[Datom]:
        t_iso = tx_time.isoformat()
        with self._lock:
            cur = self._conn.execute(
                "SELECT * FROM datom_log WHERE tx_time > ? ORDER BY seq ASC",
                (t_iso,),
            )
            rows = cur.fetchall()
        return (_decode(r) for r in rows)

    def mark_invalidated(self, tx: int, invalidated_by_tx: int) -> None:
        with self._lock:
            try:
                self._conn.execute("BEGIN IMMEDIATE")
                self._conn.execute(
                    """
                    UPDATE datom_log
                       SET invalidated_by = ?
                     WHERE tx = ?
                       AND invalidated_by IS NULL
                       AND op = 'assert'
                    """,
                    (invalidated_by_tx, tx),
                )
                self._conn.execute("COMMIT")
            except BaseException:
                self._conn.execute("ROLLBACK")
                raise

    def next_tx(self) -> int:
        """``SELECT COALESCE(MAX(tx), 0) + 1 FROM datom_log`` under lock.

        Read-only probe — see module docstring. To atomically reserve an
        id, use :meth:`allocate_and_append`.
        """
        with self._lock:
            cur = self._conn.execute(
                "SELECT COALESCE(MAX(tx), 0) + 1 FROM datom_log"
            )
            row = cur.fetchone()
        # Result is either a Row (when row_factory=Row) or a plain tuple.
        return int(row[0] if row is not None else 1)

    # ------- Additive Protocol methods (PG3 / ADR-15 W2) ------------------

    @contextmanager
    def _txn(self):
        """Default transaction context — SQLiteStore relies on per-method BEGIN IMMEDIATE.

        Each existing method (``append`` / ``allocate_and_append`` /
        ``mark_invalidated``) opens its own ``BEGIN IMMEDIATE`` writer-
        lock transaction and commits before returning. ``_txn()`` is a
        pass-through that yields ``None`` so the higher-level
        :meth:`transact_serializable` shape works without nesting two
        transactions (``BEGIN IMMEDIATE`` inside another ``BEGIN`` would
        raise on SQLite). Multi-step atomicity in single-process SQLite
        deployments is covered by the existing ``_lock`` mutex; the
        ``BEGIN IMMEDIATE`` boundary lives one level down on the actual
        write call.
        """
        with nullcontext():
            yield None

    def transact_serializable(
        self,
        datoms: Iterable[Datom],
        *,
        tx_time: datetime | None = None,
    ) -> int:
        """Default impl: route through :meth:`allocate_and_append` under ``_lock``.

        Per ADR-15 W2 the SQLiteStore default impl preserves existing
        single-process semantics — the in-process ``_lock`` mutex plus
        ``BEGIN IMMEDIATE`` writer-lock is the existing serialisation
        gate. When ``tx_time`` is provided, every datom's ``tx_time`` is
        overridden with it before insertion (ADR-13 preservation of the
        audit handler's ``recorded_at`` instant).
        """
        materialised = list(datoms)
        if not materialised:
            return 0
        if tx_time is not None:
            materialised = [_replace_tx_time(d, tx_time) for d in materialised]
        out = self.allocate_and_append(materialised)
        return int(out[0].tx)

    # ---- Connection management ------------------------------------------
    def close(self) -> None:
        with self._lock:
            self._conn.close()

    def __del__(self) -> None:  # best-effort cleanup
        try:
            self.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Codec shims — the canonical codec lives at ``persistence.store._codec``.
# ---------------------------------------------------------------------------
# Row <-> Datom encoding is canonical-JSON for ``v`` / ``provenance``
# (so SQLite and Postgres both store them in a TEXT column) and ISO-8601
# for the SQLite TEXT timestamp columns. PG2 (Phase 1 stream #165)
# consolidates the helpers into ``persistence.store._codec.TextDatomCodec``
# so the same canonical implementation backs both SQLite and any future
# text-wire backend; PostgresStore uses ``NativeDatomCodec`` for its
# native TIMESTAMPTZ adapter path. See ADR-16 in the design doc for the
# decision record.
#
# These module-level names stay as thin aliases so any existing import
# of ``from persistence.fact.store import _encode, _decode, _with_tx,
# TX_PLACEHOLDER`` continues to resolve unchanged. The body is a single
# delegation to the codec instance.


def _encode(d: Datom) -> tuple:
    """Encode a Datom for SQLite — TEXT-wire shape via :class:`TextDatomCodec`."""
    return _codec.encode(d)


def _decode(row) -> Datom:
    """Decode a SQLite row back into a Datom via :class:`TextDatomCodec`.

    ``row`` may be a :class:`sqlite3.Row` (mapping access by column name,
    used by SQLiteStore's read paths) or a positional tuple (older test
    fixtures). The codec accepts both shapes via feature detection.
    """
    return _codec.decode(row)


#: Sentinel value used in place of a real tx id while a transaction's
#: datoms are being assembled upstream (see ``DB.transact``). When
#: :meth:`Store.allocate_and_append` stamps the real tx, it also rewrites
#: any provenance key pointing at the sentinel (e.g. ``superseded_by_tx``)
#: so downstream readers never observe the placeholder. Kept as -1 (an
#: impossible real tx) so a stray leak fails loudly in tests.
TX_PLACEHOLDER: int = _CODEC_TX_PLACEHOLDER


def _with_tx(d: Datom, tx: int) -> Datom:
    """Return a copy of ``d`` with ``tx`` replaced.

    Thin alias around :func:`persistence.store._codec.with_tx` so that
    existing imports of ``persistence.fact.store._with_tx`` keep
    resolving. Behaviour is byte-identical: rewrites any provenance
    value equal to :data:`TX_PLACEHOLDER` to ``tx``, leaves everything
    else untouched.
    """
    return _shared_with_tx(d, tx)


def _replace_tx_time(d: Datom, tx_time: datetime) -> Datom:
    """Return a copy of ``d`` with ``tx_time`` replaced — frozen-Datom safe.

    Used by :meth:`Store.transact_serializable` to honour the optional
    ``tx_time`` argument. Per ADR-13 the audit-chain migration must
    preserve the audit handler's ``recorded_at`` instant: the audit
    handler stamps the entry's ``recorded_at`` at the moment the audit
    fires, NOT at the moment the datom commits. Without this override,
    ``transact_serializable`` would route through ``allocate_and_append``
    which preserves whatever ``tx_time`` lives on the input datom — but
    this helper makes the override explicit at the Protocol level so
    callers don't have to construct a new Datom themselves.
    """
    return Datom(
        e=d.e,
        a=d.a,
        v=d.v,
        tx=d.tx,
        tx_time=tx_time,
        valid_from=d.valid_from,
        valid_to=d.valid_to,
        op=d.op,
        provenance=d.provenance,
        invalidated_by=d.invalidated_by,
    )


__all__ = ["InMemoryStore", "SQLiteStore", "Store", "load_migrations"]
