"""String-building emit functions for persistence-orchestrate.

LD-2 (codex consensus DISAGREE-STRONG → D-3 Mixed): pure stdlib
emitter (no Jinja2, no LLM-driven generation). Templates are fixed;
emit functions build strings deterministically.

4 emitters per LD-1 (4-file emitted dir):
- emit_skill_md(chain) → str          [SKILL.md, marketplace artifact]
- emit_chain_edn(chain) → str         [chain.edn, canonical chain]
- emit_preflight_toml(chain) → str    [preflight.toml, capability allowlist]
- emit_orchestrate_py(chain) → str    [orchestrate.py, thin runner]

The orchestrate.py emitter renders a pure-Python module exposing
run_chain(substrate, granted_capabilities) using s.effect.perform()
per step.
"""
from __future__ import annotations

from pathlib import Path

from persistence.orchestrate._schema import Chain, serialize_chain_edn

# Canonical install-prereqs region for emitted SKILL.md (LD-4 verbatim).
# R0-fold B1: clone+uv-sync clause sourced from positioning.md:98;
# mintkey/UNSET is NEW extension text grounded in CLAUDE.md:32 +
# positioning.md:21-23.
PREREQS_REGION = """## Prerequisites

This skill requires persistence-os installed locally:

Clone `persistence-os`, run `uv sync`

For signed audit chains (production posture), generate an Ed25519 key:

  python -m persistence.tools.mintkey --out ~/.persistence/keys/agent.pem
  export PERSISTENCE_AUDIT_KEY=file:///$HOME/.persistence/keys/agent.pem

For dev mode (unsigned), UNSET the env var:

  unset PERSISTENCE_AUDIT_KEY

The skill invokes `python ./orchestrate.py` directly."""


def emit_skill_md(chain: Chain) -> str:
    """Render the marketplace SKILL.md for an emitted chain."""
    return f"""---
name: {chain.name}
description: {chain.description}
---

# {chain.name}

{chain.description}

<!-- prereqs-begin -->
{PREREQS_REGION}
<!-- prereqs-end -->

## What this skill does

When invoked, this skill runs the chain defined in `chain.edn` using
the persistence-os substrate. Each step is gated by a Capability from
the 2.3d lattice; the run produces a signed canonical_audit_stack
trace replayable byte-identically.

## How to run

```bash
python ./orchestrate.py
```

## Files in this skill

- `SKILL.md` — this file
- `chain.edn` — canonical chain definition
- `preflight.toml` — capabilities + ops required
- `orchestrate.py` — the chain runner using `persistence.sdk`
"""


def emit_chain_edn(chain: Chain) -> str:
    """Re-serialize the chain to canonical EDN form."""
    return serialize_chain_edn(chain)


def emit_preflight_toml(chain: Chain) -> str:
    """Render preflight.toml: capabilities + ops required by this chain.

    Mirrors the schema shape of tests/preflight_manifest.toml shipped
    in 2.4c (FD-PREFLIGHT-TOML-SCHEMA default).
    """
    lines = [
        "# Preflight manifest for this chain — generated by",
        "# persistence-orchestrate. DO NOT EDIT.",
        "",
        f'name = "{chain.name}"',
        "",
        "[capabilities]",
    ]
    # Sorted unique capabilities for determinism
    caps = sorted({
        (s.capability.op, s.capability.qualifier)
        for s in chain.steps if s.capability is not None
    })
    for op, qual in caps:
        lines.append(f'{op}_{qual} = {{ op = "{op}", qualifier = "{qual}" }}')

    lines.append("")
    lines.append("[ops]")
    ops = sorted({s.op for s in chain.steps})
    for op in ops:
        lines.append(f'"{op}" = {{ required = true }}')
    lines.append("")
    return "\n".join(lines)


def emit_orchestrate_py(chain: Chain) -> str:
    """Render orchestrate.py — the thin chain runner.

    The emitted module exposes:
      run_chain(substrate, granted_capabilities) -> None

    which loops the chain's steps and invokes s.effect.perform per step
    under the substrate's canonical_audit_stack. Capability gating uses
    the 2.3d lattice; pause/resume steps emit :repl/request +
    :repl/response audit pairs (LD-1 5-capability showcase).
    """
    # Sorted unique op set (excluding :capability/denied — always installed)
    # for determinism per LD-2 byte-identity contract.
    chain_ops_sorted = sorted({step.op for step in chain.steps})
    # Build the install-on-chain set: only ops that the canonical
    # audit stack does NOT already cover end-to-end. Substrate-native
    # ops (raw RAW_OPS, plus :sys/now via the sys_now handler) have
    # working terminators; we still want them surfaced in the audit
    # chain for the 5-capability showcase. The runner installs a
    # dedicated audit-emitting handler that wraps EVERY chain op
    # (plus :capability/denied) so each step produces exactly one
    # signed AuditEntry — uniform shape for the LD-1 falsifier.
    chain_ops_repr = "[" + ", ".join(repr(op) for op in chain_ops_sorted) + "]"

    header = f'''"""Emitted orchestrator for chain {chain.name!r}.

Generated by persistence-orchestrate; do not edit by hand.
Re-emit from chain.edn if the chain changes.

LD-1: this is the "thin orchestrator that calls the curated SDK
surface" per codex A-prime. Pure Python; no Coder involvement.
"""
from __future__ import annotations

from collections.abc import Iterable

# Capability lives in `persistence.repl._caps` (the v0.7.0a1 closed-set
# ADT, see ADR-3 of the Module 7 design doc). It is intentionally NOT
# re-exported from `persistence.sdk` in v0.9.0a1 — the curated SDK
# surface re-exports plan/fact/txn types only, and the cap ADT is a
# REPL-module concept. Adapter authors who need it bind directly to
# the repl module as a stable import path (the closed set is itself
# the v0.7.0a1 forward-compat contract; see ``ALL_CAPS``).
from persistence.repl._caps import Capability
from persistence.sdk import Substrate


# Chain ops the runner installs audit-emitting wrappers for.
# Canonical audit stack only wraps the v0.5.x..v0.9.0a1
# substrate-native ops (CANONICAL_AUDIT_WRAPPED_OPS); chain-emitted
# ops outside that set need their own audit handler so AuditEntries
# show up in substrate._audit_entries with the configured signer.
_ORCHESTRATE_CHAIN_OPS: tuple[str, ...] = tuple({chain_ops_repr})

# Ops that return non-JSON-serialisable values (e.g. ``:sys/now`` returns
# a bare ``datetime.datetime``) cannot be audited via
# ``make_audit_handler`` because the audit clause hashes the result.
# For these we install a custom audit clause that emits an entry with
# ``result_hash=None`` and passes the value through unchanged.
_VIEW_OPS_DATETIME_RETURN: frozenset[str] = frozenset({{":sys/now"}})


def _install_orchestrate_handlers(substrate: Substrate) -> None:
    """Install audit-emitting handlers + no-op terminators for each
    chain op and for ``:capability/denied``.

    Per-op audit handler:
      - shares ``substrate._audit_entries`` so chain ops appear in the
        same Merkle chain as substrate-native ops,
      - inherits the substrate's signer (recovered from the running
        canonical ``audit`` handler) so chain entries are signed
        identically.

    Per-op terminator:
      - returns None for ops the canonical stack does NOT already
        terminate (e.g. :capability/denied).

    View ops with datetime returns (``:sys/now``) get a custom
    audit-emitting clause that records a signed AuditEntry with
    ``result_hash=None`` instead of running through ``make_audit_handler``
    (whose result-hashing path can't canonicalise datetimes).

    Idempotent — re-installation replaces by ``name``.
    """
    from persistence.effect.handlers.audit import make_audit_handler
    from persistence.effect.runtime import Handler

    # Recover signer from the canonical ``audit`` handler so chain
    # entries are signed identically. None when audit is unsigned.
    signer = None
    for h in substrate._runtime.handlers:
        if h.name == "audit":
            signer = h.ctx.get("signer")
            break

    ops_to_wrap = tuple(_ORCHESTRATE_CHAIN_OPS) + (":capability/denied",)

    for op in ops_to_wrap:
        sanitized = op.lstrip(":").replace("/", "-")

        if op in _VIEW_OPS_DATETIME_RETURN:
            # Custom audit-emitting wrapper for view ops with non-JSON
            # return values. Records a signed AuditEntry with
            # result_hash=None; passes the underlying value through.
            handler = _make_view_op_audit_handler(
                op,
                substrate._audit_entries,
                signer=signer,
                handler_name=f"orchestrate-audit-{{sanitized}}",
            )
            substrate.effect.install_handler(handler, position="top")
            # No terminator install — canonical stack's sys_now handler
            # is the terminator for :sys/now.
            continue

        # Standard audit middleware for ops with JSON-serialisable
        # (or None) returns.
        handler = make_audit_handler(
            substrate._audit_entries,
            wraps={{op}},
            signer=signer,
        )
        handler.name = f"orchestrate-audit-{{sanitized}}"

        terminator = Handler(
            name=f"orchestrate-term-{{sanitized}}",
            wraps={{op}},
            clauses={{op: lambda _args, _k, _ctx: None}},
        )
        substrate.effect.install_handler(terminator, position="bottom")
        substrate.effect.install_handler(handler, position="top")


def _make_view_op_audit_handler(
    op: str,
    entries: list,
    *,
    signer: "tuple[str, bytes] | None",
    handler_name: str,
):
    """Build a Handler that emits a signed AuditEntry for a view op
    whose return value is non-JSON-serialisable (e.g. datetime).

    Unlike ``make_audit_handler``, this clause:
      - does NOT hash the result (``result_hash`` is fixed to None),
      - calls ``k(args)`` to delegate to the downstream view handler
        (e.g. ``sys_now``) and returns its value unchanged,
      - signs the entry via ``_signing.sign`` when ``signer`` is set,
        matching the canonical audit handler's signing contract.

    Phase 7 LD-1 specialisation: substrate-time (cap 5) is surfaced
    in the audit chain WITHOUT changing the substrate-native
    ``sys_now`` handler or the canonical audit stack composition.

    Implementation note: this clause does NOT recompute the
    canonical-AuditEntry content hash byte-for-byte against
    ``make_audit_handler``'s shape — instead it computes a
    self-consistent ``id = canonical_hash(content)`` over the dict
    used to construct the entry. The resulting AuditEntry verifies
    its own signature with ``persistence.effect.verify`` but is NOT
    chain-equivalent to a canonical entry of the same op. View ops
    are orchestrator-side enrichments to the Merkle chain; treat
    them as supplementary to substrate-native entries, not equivalent.
    """
    from persistence.effect.canonical import canonical_hash
    from persistence.effect.handlers.audit import AuditEntry
    from persistence.effect.runtime import Handler, mask, perform

    def clause(args, k, ctx):
        args_hash = canonical_hash(args)
        with mask("audit"):
            t0 = perform(":clock/now")["ts"]
        verdict = "ok"
        error_str: "str | None" = None
        try:
            return k(args)
        except BaseException as exc:  # noqa: BLE001
            verdict = "error"
            error_str = f"{{type(exc).__name__}}: {{exc}}"
            raise
        finally:
            with mask("audit"):
                t1 = perform(":clock/now")["ts"]
            latency_ms = max(0, int((t1 - t0) * 1000))
            prev_hash = entries[-1].id if entries else None
            content = {{
                "prev_hash": prev_hash,
                "op": op,
                "args_hash": args_hash,
                "verdict": verdict,
                "latency_ms": latency_ms,
                "recorded_at": t1,
                "result_hash": None,
                "error": error_str,
                "policy_id": None,
                "handler_chain": (),
                "principal": {{}},
                "run_id": None,
                "parent": prev_hash,
                "parent_audit_entry_id": None,
            }}
            entry_id = canonical_hash(content)
            sig_kwargs: dict = {{}}
            if signer is not None:
                from persistence.effect._signing import sign as _sign
                signer_id, private_key = signer
                sig_kwargs["signature"] = _sign(entry_id, private_key)
                sig_kwargs["signer_id"] = signer_id
            entries.append(
                AuditEntry(id=entry_id, **content, **sig_kwargs)
            )

    return Handler(
        name=handler_name,
        wraps={{op}},
        clauses={{op: clause}},
    )


def run_chain(
    substrate: Substrate,
    granted_capabilities: Iterable[Capability],
) -> None:
    """Run the {chain.name!r} chain under `substrate`.

    `granted_capabilities` controls which steps are allowed to execute;
    steps whose required capability is not granted emit a
    :capability/denied audit entry and are skipped (LD-1 falsifier).
    """
    granted = set(granted_capabilities)
    _install_orchestrate_handlers(substrate)

'''

    body_parts = []
    for step in chain.steps:
        cap = step.capability
        args_repr = repr(step.args)
        if cap is not None:
            body_parts.append(f'''    # Step {step.id}: {step.op}
    _step_{step.id}_cap = Capability(op={cap.op!r}, qualifier={cap.qualifier!r})
    if _step_{step.id}_cap not in granted:
        substrate.effect.perform(
            ":capability/denied",
            {{":step_id": {step.id}, ":required_op": {cap.op!r}, ":required_qualifier": {cap.qualifier!r}}},
        )
    else:
        substrate.effect.perform({step.op!r}, {args_repr})
''')
        else:
            body_parts.append(f'''    # Step {step.id}: {step.op} (no capability gate)
    substrate.effect.perform({step.op!r}, {args_repr})
''')

    body = "\n".join(body_parts)
    return header + body


def emit_orchestrator_skill(chain: Chain, out_dir: Path) -> None:
    """Top-level emit: render 4 files into `out_dir`."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "SKILL.md").write_text(emit_skill_md(chain))
    (out_dir / "chain.edn").write_text(emit_chain_edn(chain))
    (out_dir / "preflight.toml").write_text(emit_preflight_toml(chain))
    (out_dir / "orchestrate.py").write_text(emit_orchestrate_py(chain))
