"""String-building emit functions for persistence-orchestrate.

LD-2 (codex consensus DISAGREE-STRONG → D-3 Mixed): pure stdlib
emitter (no Jinja2, no LLM-driven generation). Templates are fixed;
emit functions build strings deterministically.

4 emitters per LD-1 (4-file emitted dir):
- emit_skill_md(chain) → str          [SKILL.md, marketplace artifact]
- emit_chain_edn(chain) → str         [chain.edn, canonical chain]
- emit_preflight_toml(chain) → str    [preflight.toml, capability allowlist]
- emit_orchestrate_py(chain) → str    [orchestrate.py, thin runner]

The orchestrate.py emitter renders a pure-Python module exposing
run_chain(substrate, granted_capabilities) using s.effect.perform()
per step.
"""
from __future__ import annotations

from pathlib import Path

from persistence.orchestrate._schema import Chain, serialize_chain_edn

# Canonical install-prereqs region for emitted SKILL.md (LD-4 verbatim).
# R0-fold B1: clone+uv-sync clause sourced from positioning.md:98;
# mintkey/UNSET is NEW extension text grounded in CLAUDE.md:32 +
# positioning.md:21-23.
PREREQS_REGION = """## Prerequisites

This skill requires persistence-os installed locally:

Clone `persistence-os`, run `uv sync`

For signed audit chains (production posture), generate an Ed25519 key:

  python -m persistence.tools.mintkey --out ~/.persistence/keys/agent.pem
  export PERSISTENCE_AUDIT_KEY=file:///$HOME/.persistence/keys/agent.pem

For dev mode (unsigned), UNSET the env var:

  unset PERSISTENCE_AUDIT_KEY

The skill invokes `python ./orchestrate.py` directly."""


def emit_skill_md(chain: Chain) -> str:
    """Render the marketplace SKILL.md for an emitted chain."""
    return f"""---
name: {chain.name}
description: {chain.description}
---

# {chain.name}

{chain.description}

<!-- prereqs-begin -->
{PREREQS_REGION}
<!-- prereqs-end -->

## What this skill does

When invoked, this skill runs the chain defined in `chain.edn` using
the persistence-os substrate. Each step is gated by a Capability from
the 2.3d lattice; the run produces a signed canonical_audit_stack
trace replayable byte-identically.

## How to run

```bash
python ./orchestrate.py
```

## Files in this skill

- `SKILL.md` — this file
- `chain.edn` — canonical chain definition
- `preflight.toml` — capabilities + ops required
- `orchestrate.py` — the chain runner using `persistence.sdk`
"""


def emit_chain_edn(chain: Chain) -> str:
    """Re-serialize the chain to canonical EDN form."""
    return serialize_chain_edn(chain)


def emit_preflight_toml(chain: Chain) -> str:
    """Render preflight.toml: capabilities + ops required by this chain.

    Mirrors the schema shape of tests/preflight_manifest.toml shipped
    in 2.4c (FD-PREFLIGHT-TOML-SCHEMA default).
    """
    lines = [
        "# Preflight manifest for this chain — generated by",
        "# persistence-orchestrate. DO NOT EDIT.",
        "",
        f'name = "{chain.name}"',
        "",
        "[capabilities]",
    ]
    # Sorted unique capabilities for determinism
    caps = sorted({
        (s.capability.op, s.capability.qualifier)
        for s in chain.steps if s.capability is not None
    })
    for op, qual in caps:
        lines.append(f'{op}_{qual} = {{ op = "{op}", qualifier = "{qual}" }}')

    lines.append("")
    lines.append("[ops]")
    ops = sorted({s.op for s in chain.steps})
    for op in ops:
        lines.append(f'"{op}" = {{ required = true }}')
    lines.append("")
    return "\n".join(lines)


def emit_orchestrate_py(chain: Chain) -> str:
    """Render orchestrate.py — the thin chain runner.

    The emitted module exposes:
      run_chain(substrate, granted_capabilities) -> None

    which loops the chain's steps and invokes s.effect.perform per step
    under the substrate's canonical_audit_stack. Capability gating uses
    the 2.3d lattice; pause/resume steps emit :repl/request +
    :repl/response audit pairs (LD-1 5-capability showcase).
    """
    header = f'''"""Emitted orchestrator for chain {chain.name!r}.

Generated by persistence-orchestrate; do not edit by hand.
Re-emit from chain.edn if the chain changes.

LD-1: this is the "thin orchestrator that calls the curated SDK
surface" per codex A-prime. Pure Python; no Coder involvement.
"""
from __future__ import annotations

from collections.abc import Iterable

from persistence.sdk import Capability, Substrate


def run_chain(
    substrate: Substrate,
    granted_capabilities: Iterable[Capability],
) -> None:
    """Run the {chain.name!r} chain under `substrate`.

    `granted_capabilities` controls which steps are allowed to execute;
    steps whose required capability is not granted emit a
    :capability/denied audit entry and are skipped (LD-1 falsifier).
    """
    granted = set(granted_capabilities)

'''

    body_parts = []
    for step in chain.steps:
        cap = step.capability
        args_repr = repr(step.args)
        if cap is not None:
            body_parts.append(f'''    # Step {step.id}: {step.op}
    _step_{step.id}_cap = Capability(op={cap.op!r}, qualifier={cap.qualifier!r})
    if _step_{step.id}_cap not in granted:
        substrate.effect.perform(
            ":capability/denied",
            {{":step_id": {step.id}, ":required": _step_{step.id}_cap}},
        )
    else:
        substrate.effect.perform({step.op!r}, {args_repr})
''')
        else:
            body_parts.append(f'''    # Step {step.id}: {step.op} (no capability gate)
    substrate.effect.perform({step.op!r}, {args_repr})
''')

    body = "\n".join(body_parts)
    return header + body


def emit_orchestrator_skill(chain: Chain, out_dir: Path) -> None:
    """Top-level emit: render 4 files into `out_dir`."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "SKILL.md").write_text(emit_skill_md(chain))
    (out_dir / "chain.edn").write_text(emit_chain_edn(chain))
    (out_dir / "preflight.toml").write_text(emit_preflight_toml(chain))
    (out_dir / "orchestrate.py").write_text(emit_orchestrate_py(chain))
