"""String-building emit functions for persistence-orchestrate.

LD-2 (codex consensus DISAGREE-STRONG → D-3 Mixed): pure stdlib
emitter (no Jinja2, no LLM-driven generation). Templates are fixed;
emit functions build strings deterministically.

4 emitters per LD-1 (4-file emitted dir):
- emit_skill_md(chain) → str          [SKILL.md, marketplace artifact]
- emit_chain_edn(chain) → str         [chain.edn, canonical chain]
- emit_preflight_toml(chain) → str    [preflight.toml, capability allowlist]
- emit_orchestrate_py(chain) → str    [orchestrate.py, thin runner]

The orchestrate.py emitter renders a pure-Python module exposing
run_chain(substrate, granted_capabilities) using s.effect.perform()
per step.
"""
from __future__ import annotations

from pathlib import Path

from persistence.orchestrate._schema import Chain, serialize_chain_edn

# Canonical install-prereqs region for emitted SKILL.md (LD-4 verbatim).
# R0-fold B1: clone+uv-sync clause sourced from positioning.md:98;
# mintkey/UNSET is NEW extension text grounded in CLAUDE.md:32 +
# positioning.md:21-23.
PREREQS_REGION = """## Prerequisites

This skill requires persistence-os installed locally:

Clone `persistence-os`, run `uv sync`

For signed audit chains (production posture), generate an Ed25519 key:

  python -m persistence.tools.mintkey --out ~/.persistence/keys/agent.pem
  export PERSISTENCE_AUDIT_KEY=file:///$HOME/.persistence/keys/agent.pem

For dev mode (unsigned), UNSET the env var:

  unset PERSISTENCE_AUDIT_KEY

The skill invokes `python ./orchestrate.py` directly."""


def emit_skill_md(chain: Chain) -> str:
    """Render the marketplace SKILL.md for an emitted chain."""
    return f"""---
name: {chain.name}
description: {chain.description}
---

# {chain.name}

{chain.description}

<!-- prereqs-begin -->
{PREREQS_REGION}
<!-- prereqs-end -->

## What this skill does

When invoked, this skill runs the chain defined in `chain.edn` using
the persistence-os substrate. Each step is gated by a Capability from
the 2.3d lattice; the run produces a signed canonical_audit_stack
trace replayable byte-identically.

## How to run

```bash
python ./orchestrate.py
```

## Files in this skill

- `SKILL.md` — this file
- `chain.edn` — canonical chain definition
- `preflight.toml` — capabilities + ops required
- `orchestrate.py` — the chain runner using `persistence.sdk`
"""


def emit_chain_edn(chain: Chain) -> str:
    """Re-serialize the chain to canonical EDN form."""
    return serialize_chain_edn(chain)


def emit_preflight_toml(chain: Chain) -> str:
    """Render preflight.toml: capabilities + ops required by this chain.

    Mirrors the schema shape of tests/preflight_manifest.toml shipped
    in 2.4c (FD-PREFLIGHT-TOML-SCHEMA default).
    """
    lines = [
        "# Preflight manifest for this chain — generated by",
        "# persistence-orchestrate. DO NOT EDIT.",
        "",
        f'name = "{chain.name}"',
        "",
        "[capabilities]",
    ]
    # Sorted unique capabilities for determinism
    caps = sorted({
        (s.capability.op, s.capability.qualifier)
        for s in chain.steps if s.capability is not None
    })
    for op, qual in caps:
        lines.append(f'{op}_{qual} = {{ op = "{op}", qualifier = "{qual}" }}')

    lines.append("")
    lines.append("[ops]")
    ops = sorted({s.op for s in chain.steps})
    for op in ops:
        lines.append(f'"{op}" = {{ required = true }}')
    lines.append("")
    return "\n".join(lines)


def emit_orchestrate_py(chain: Chain) -> str:
    """Render orchestrate.py — the thin chain runner.

    The emitted module exposes:
      run_chain(substrate, granted_capabilities) -> None

    which loops the chain's steps and invokes ``s.effect.perform`` per
    step under the substrate's canonical audit stack. Capability gating
    uses the 2.3d lattice; missing capabilities emit a signed
    ``:capability/denied`` AuditEntry and skip the step.

    R1-fold substrate-truth rewrite (B2 + B3):

    - No view-op audit shim. ``:sys/now`` returns a ``datetime.datetime``
      directly and emits NO audit entry by default (substrate truth —
      ``sys_now`` is a view handler, not a wrapped op). Cap 5 (substrate-time)
      is demonstrated by the G5 harness calling
      ``substrate.effect.perform(":sys/now", {})`` directly.
    - No no-op terminator masking. The runner installs only handlers it
      can guarantee end-to-end behaviour for: the ``raw-echo`` LLM
      handler at the bottom of the stack (terminator for ``:llm/call``)
      and one audit middleware wrapping ``:capability/denied`` so denial
      records share the canonical chain's signer + signing contract.
    - Chain ops outside the substrate-native set (i.e. anything the
      canonical audit stack does NOT cover) will RAISE on perform — by
      design. The orchestrator does not silently mask missing handlers.
    """
    header = f'''"""Emitted orchestrator for chain {chain.name!r}.

Generated by persistence-orchestrate; do not edit by hand.
Re-emit from chain.edn if the chain changes.

LD-1: this is the "thin orchestrator that calls the curated SDK
surface" per codex A-prime. Pure Python; no Coder involvement.
"""
from __future__ import annotations

from collections.abc import Iterable

# Capability is re-exported from ``persistence.sdk`` as of v0.9.0a1
# (R1-fold I1). Adapter authors bind through the curated SDK surface;
# the underlying ADT still lives in ``persistence.repl._caps`` (closed
# set per ADR-3, v0.7.0a1 forward-compat contract).
from persistence.sdk import Capability, Substrate


def _install_orchestrate_handlers(substrate: Substrate) -> None:
    """Install the two handlers the runner needs end-to-end.

    Substrate-truth rewrite (R1-fold B2 + B3):

    - ``raw-echo`` at ``position="bottom"`` → terminator for
      ``:llm/call``. ``Substrate.open`` does NOT install an LLM
      provider by default; without this, every ``:llm/call`` would
      bubble past the canonical audit middleware with no terminator
      and raise. ``make_echo_llm_handler`` is the substrate-truth
      bottom handler used in tests and demos.

    - ``orchestrate-audit-capability-denied`` at ``position="top"`` →
      audit middleware wrapping ``:capability/denied`` (the
      orchestrator's own signaling op; NOT in
      ``CANONICAL_AUDIT_WRAPPED_OPS``). Reuses the canonical audit
      stack's signer so denial entries are signed identically to
      substrate-native entries.

    Idempotent — ``install_handler`` replaces by ``name``.
    """
    from persistence.effect.handlers.audit import make_audit_handler
    from persistence.effect.handlers.raw import make_echo_llm_handler
    from persistence.effect.runtime import Handler

    # Recover signer from the canonical ``audit`` handler so denial
    # entries inherit the same signing contract (None when unsigned).
    signer = None
    for h in substrate._runtime.handlers:
        if h.name == "audit":
            signer = h.ctx.get("signer")
            break

    echo = make_echo_llm_handler()
    substrate.effect.install_handler(echo, position="bottom")

    # Terminator for :capability/denied — the orchestrator's own
    # signaling op (request-as-audit-signal pattern, mirrors the
    # canonical raw terminator's treatment of ``:claim/emit`` /
    # ``:repl/request``). Returns None; no further side effect. Scoped
    # to exactly ``:capability/denied`` so it canNOT mask missing
    # handlers for arbitrary chain ops (R1-fold B3).
    denial_term = Handler(
        name="orchestrate-term-capability-denied",
        wraps={{":capability/denied"}},
        clauses={{":capability/denied": lambda _args, _k, _ctx: None}},
    )
    substrate.effect.install_handler(denial_term, position="bottom")

    denial_audit = make_audit_handler(
        substrate._audit_entries,
        wraps={{":capability/denied"}},
        signer=signer,
    )
    denial_audit.name = "orchestrate-audit-capability-denied"
    substrate.effect.install_handler(denial_audit, position="top")


def run_chain(
    substrate: Substrate,
    granted_capabilities: Iterable[Capability],
) -> None:
    """Run the {chain.name!r} chain under `substrate`.

    `granted_capabilities` controls which steps are allowed to execute;
    steps whose required capability is not granted emit a
    :capability/denied audit entry and are skipped (LD-1 falsifier).
    """
    granted = set(granted_capabilities)
    _install_orchestrate_handlers(substrate)

'''

    body_parts = []
    for step in chain.steps:
        cap = step.capability
        args_repr = repr(step.args)
        if cap is not None:
            body_parts.append(f'''    # Step {step.id}: {step.op}
    _step_{step.id}_cap = Capability(op={cap.op!r}, qualifier={cap.qualifier!r})
    if _step_{step.id}_cap not in granted:
        substrate.effect.perform(
            ":capability/denied",
            {{"step_id": {step.id}, "required_op": {cap.op!r}, "required_qualifier": {cap.qualifier!r}}},
        )
    else:
        substrate.effect.perform({step.op!r}, {args_repr})
''')
        else:
            body_parts.append(f'''    # Step {step.id}: {step.op} (no capability gate)
    substrate.effect.perform({step.op!r}, {args_repr})
''')

    body = "\n".join(body_parts)
    return header + body


def emit_orchestrator_skill(chain: Chain, out_dir: Path) -> None:
    """Top-level emit: render 4 files into `out_dir`."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "SKILL.md").write_text(emit_skill_md(chain))
    (out_dir / "chain.edn").write_text(emit_chain_edn(chain))
    (out_dir / "preflight.toml").write_text(emit_preflight_toml(chain))
    (out_dir / "orchestrate.py").write_text(emit_orchestrate_py(chain))
